name: pl_dungeon
version: '1.0-SNAPSHOT'
main: com.takutou.pl_dungeon.Pl_dungeon
api-version: '1.20'
commands:
  dungeonmoblist:
    description: /dungeonmoblist
  dungeon:
    description: /dungeon <num>
  dungeoncreate:
    description: /dungeoncreate mobName speed maxHealth attackDamage
